language: php
php:
    - '7.4snapshot'
    - nightly
matrix:
    allow_failures:
        - php: nightly
before_script: composer install
script:
    - vendor/bin/phpunit --coverage-clover=coverage.clover
    - vendor/bin/psalm
